### PR TITLE
feat: Http Client for accessing OpenSauced API client

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

Integrates using the opensauced api client for doing "bake" operations and sets the president for using the `--beta` and `--endpoint` global flags.

Example usage:

```
❯ pizza bake --beta https://github.com/jpmcb/gopherlogs
Using beta API endpoint - https://beta.api.opensauced.pizza/v1
Resp body:
```

(note that at the time of this PR, the prod API has not merged change to normalize the requests for the `/bake` route so only the beta API is working. Use the `--beta` global flag when testing 😄 )

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to https://github.com/open-sauced/api/issues/218

## Mobile & Desktop Screenshots/Recordings

N/a

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by jpmcb** [comment]
Tomorrow I'll also look at integrating this with the other commands that make calls to the OpenSauced APIs / tools

**Review by bdougie — APPROVED** [review]
This is nice and I am super excited to start kicking this thing around once we add some features to it. Thanks for all the work on these PRs @jpmcb & @k1nho!

**Comment by jpmcb** [comment]
Force pushed:
- resolve conflicts on `main`
- adjusted the repo-query to use an API client (would be good to get @diivi eyes on this)
  - The flow of this is abit odd since the repo-query doesn't really use the default API endpoint. But, this is nice for someone to be able to set the `--endpoint` flag to a custom repo-query endpoint to do some testing and validation.

**Review by brandonroberts — APPROVED** [review]
The explanation on the custom endpoint helped

**Pull request merged**
