### PR TITLE
fix: add calculation to display correct pull request velocity

### LINKED ISSUE #45: Bug: pr velocity inaccurate in pizza show
### Describe the bug

PR velocity is using the ```recent_pull_request_velocity_count ``` field which is not representative of the actual percentage metric that needs to be displayed.

We need to use ```recent_pull_requests_count``` which is the one over 30 days, and do something like (recent_pull_request_count/30) * 100 to get the actual percentage.

### Steps to reproduce

Go into the contributor view and check the PR velocity metric.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by k1nho**
## Description

This PR adds a calculation to get the correct pull request velocity percentage to display. It calculates the percentage with the same formula implemented by the```getPercent(total, count)``` method. This approach is used in ```dev-card``` component via ```getPercent(prTotal, mergedPrs)``` to render the percentage in the ```VelocityPill```.

https://github.com/open-sauced/app/blob/5b15a49d6dfbd371799d7dbf81cd5cbfef5e1d60/lib/utils/get-percent.ts#L1

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #45 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

bug

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
This is great!! 👏🏼 I think this needs just abit more to be in line with what we surface in the insights app. For example, on Nick's profile:

Screenshot 2023-10-02 at 2 10 49 PM

and in the `pizza show`:

Screenshot 2023-10-02 at 2 11 35 PM

So, the `80` in this case should really be "80% merged" which represents the percent of merged prs within the given time frame. And we should also surface `1d` which represents that averge velocity of prs to merge. You should be able to pull off the
```
m.userInfo.RecentPullRequestVelocityCount
```
which gets surfaced off the API.

So something like this (ignore the poorly formatted table 🙈 )?

```
  │                  nickytonline                  │
  │                                                │
  │ 🔥 PR Velocity (30d): 1d - 80% merged    📄 Issues: 50    │
  │                                                │
  │                                                │
  │ 🚀 PR Count (30d): 17      🔨 Maintainer: true │
  │                                                │
```

**Comment by k1nho** [comment]
Thanks for the feedback! I understand better this metric. I always though it referred to the percentage, but reading through this issue was helpful [refactor: update pr velocity indicator](https://github.com/open-sauced/app/pull/707)

**Review by jpmcb — APPROVED** [review]
🕺🏼

**Review by brandonroberts — APPROVED** [review]
📈

**Pull request merged**
