### PR TITLE
feat: Add "pizza insights user-contributions" command

### LINKED ISSUE #43: Feature / spike: `pizza insights user-contributions` for summarising user contributions to a given repos
### Type of feature

🍕 Feature

### Current behavior

There's not a great way to get fine grained details on the CLI about what individuals are doing within given repo projects.

We should support a insights command that gets that fine grained data.

This issue is more or less an exploration so I'll grab this since it'll probably take some diving into our data to understand how to put this together. Command name pending (open to ideas!)

### Suggested solution

```
❯ pizza insights user-contributions -h

Get summarized contribution data on individual contributors for a list of repositories

Usage:
  pizza insights user-contributions [flags] <repos-list>

Flags:
  -o --output   Output in <yaml|json|csv>
  -f, --file string  Path to yaml file containing an array of git repository urls
  -h, --help         help for contributors
  -p, --period int   Number of days, used for query filtering (default 30)

Global Flags:
      --beta                Shorthand for using the beta OpenSauced API endpoint ("https://beta.api.opensauced.pizza"). Supersedes the '--endpoint' flag
      --disable-telemetry   Disable sending telemetry data to OpenSauced
  -e, --endpoint string     The API endpoint to send requests to (default "https://api.opensauced.pizza")
```

Executing this on like `pizza insights user-contributions https://github.com/open-sauced/api` should return something like:

```
❯ pizza insights user-contributions https://github.com/open-sauced/api

User            Total   Authored   Co-Authored   Reviews
jpmcb           10      4          1             5
brandonroberts  10      4          1             5
```

Partly inspired by: https://docs.brew.sh/Manpage#contributions-useremailusername---repositories---csv

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

This adds the `user-contributions` command:

```
❯ pizza insights user-contributions https://github.com/open-sauced/api https://github.com/open-sauced/app
https://github.com/open-sauced/app
User                Total      Commits    PRs Created
289Volts            14         13         1
5hraddha            47         40         7
aryanas159          27         24         3
ATREAY              2          1          1
babblebey           14         12         2
brainconnect93      7          5          2
brandonroberts      368        334        34
CBID2               3          2          1
Code-Victor         2          1          1
Deadreyo            8          6          2
diivi               3          2          1
foxyblocks          24         22         2
FrancoLab           4          3          1
Gourav2609          15         13         2
heysagnik           6          5          1
Hiperultimate       5          4          1
itskish0re          9          5          4
jpmcb               6          5          1
lalitkumawat1m      1          0          1
Lucif3r-in          3          2          1
nickytonline        156        136        20
OgDev-01            165        135        30
RitaDee             47         39         8
ryuk-jayant         3          2          1
Satoshi-Sh          6          3          3
saurabh-nahar       1          0          1
shamimbinnur        1          0          1
shavidze            2          0          2
shelar1423          6          3          3
smrkhan21           2          1          1
SoundaryaKoutharapu 4          3          1
tarunclub           2          1          1

https://github.com/open-sauced/api
User           Total      Commits    PRs Created
brandonroberts 4          0          4
Hack-Light     3          0          3
jpmcb          6          0          6
OgDev-01       1          0          1
shavidze       2          0          2
```

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #43 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by jpmcb** [comment]
Ready for review: supports all the output formats (including `csv`) and supports multiple repositories at once

**Comment by brandonroberts** [comment]
@jpmcb the numbers for `open-sauced/api` for me look a bit low. Is this for the last 30 days?

**Comment by jpmcb** [comment]
@brandonroberts - they are abit low: I actually noticed that two, when compared to beta: https://beta.api.opensauced.pizza/#/Repository%20service/findAllContributorsByRepoId

```json
[
  {
    "login": "brandonroberts",
    "commits": 66,
    "prs_created": 10,
    "total_contributions": 76
  },
  {
    "login": "Hack-Light",
    "commits": 10,
    "prs_created": 3,
    "total_contributions": 13
  },
  {
    "login": "jpmcb",
    "commits": 27,
    "prs_created": 15,
    "total_contributions": 42
  },
  {
    "login": "nickytonline",
    "commits": 1,
    "prs_created": 1,
    "total_contributions": 2
  },
  {
    "login": "OgDev-01",
    "commits": 9,
    "prs_created": 2,
    "total_contributions": 11
  },
  {
    "login": "shavidze",
    "commits": 2,
    "prs_created": 2,
    "total_contributions": 4
  }
]
```

I _think_ this is because we didn't get the contributions PR merged to `main` in the API repo until after the last time that PRs were fetched for that repo in the db:

```
last_fetched_prs_at
2023-10-05 15:38:30.357
```

which seems odd that `open-sauced/api` _wouldn't_ have been updated in over 2 weeks 🤔 

regardless, it may be worth picking this up in the API since all the go code is doing is consuming that API endpoint.

**Comment by brandonroberts** [comment]
👍

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
